export function getRegionContext(region: string, professionLabel: string): string {
  const contexts: Record<string, string> = {
    "London": `London has the UK's most concentrated private healthcare market, with hundreds of independent clinics, Harley Street specialists, and major private hospital groups competing for qualified professionals. ${professionLabel} roles in London typically command a 10–20% salary premium over the national average, reflecting both cost of living and the volume of high-end private practice activity across the capital.`,

    "South East": `The South East has one of the highest concentrations of private healthcare outside London, driven by strong household incomes and proximity to the capital. Cities including Brighton, Southampton, Oxford, and Reading have well-established private clinics and independent practice networks. ${professionLabel} roles in the South East are consistently in demand, with practices often competing directly with London employers for talent.`,

    "South West": `The South West's private healthcare market is anchored by Bristol, Bath, Exeter, and Bournemouth, where independent practices have grown significantly alongside the NHS. The region attracts professionals seeking a better quality of life while maintaining strong private practice earnings. ${professionLabel} roles across the South West have grown steadily, particularly in coastal and market-town locations where NHS provision is limited.`,

    "East of England": `The East of England — spanning Cambridge, Norwich, Chelmsford, and Ipswich — has seen sustained growth in private healthcare as NHS waiting times have driven patients toward independent providers. The region's mix of affluent commuter towns and university cities creates steady demand for private clinical services. ${professionLabel} practices in this region frequently seek qualified professionals who can serve both independent and corporate clinic networks.`,

    "East Midlands": `The East Midlands encompasses Nottingham, Leicester, Derby, and Lincoln — cities with established private healthcare sectors and growing independent practice networks. The region offers an attractive combination of competitive salaries, lower cost of living than the South East, and strong career development opportunities. ${professionLabel} demand in the East Midlands has grown as NHS pressures have accelerated the shift toward private care.`,

    "West Midlands": `Birmingham is the UK's second-largest city and the commercial heart of the West Midlands private healthcare market. The region also includes Coventry, Wolverhampton, and Stoke-on-Trent, all of which have active independent clinical sectors. ${professionLabel} roles in the West Midlands are served by a mix of single-site independents and multi-site private healthcare groups, offering candidates a range of practice environments.`,

    "Yorkshire": `Yorkshire's private healthcare sector is centred on Leeds, Sheffield, and York, with a growing number of independent practices and private hospital facilities. The region combines competitive salaries with significantly lower living costs than London and the South East, making it an attractive market for qualified professionals. ${professionLabel} practices across Yorkshire are increasingly active recruiters, particularly as the region's population continues to grow.`,

    "North West": `The North West — led by Manchester and Liverpool — has one of the most active private healthcare markets outside London. Manchester in particular has seen rapid growth in private clinical services, with a dense concentration of independent clinics and corporate healthcare operators. ${professionLabel} roles in the North West are in high demand, driven by both population size and growing private healthcare uptake across the region.`,

    "North East": `The North East, including Newcastle, Sunderland, and Middlesbrough, has a smaller private healthcare footprint than other UK regions but is growing as NHS capacity constraints push more patients toward independent providers. ${professionLabel} practitioners in the North East can command competitive packages, often with the benefit of lower living costs and a strong community of local practices. The region represents an opportunity for professionals seeking roles with genuine impact in a developing private market.`,

    "Scotland": `Scotland's private healthcare sector is concentrated in Edinburgh and Glasgow, with a growing number of independent practices serving both local and medical-tourism patients. The regulatory environment in Scotland differs slightly from England and Wales, with the Care Inspectorate overseeing independent healthcare providers. ${professionLabel} roles in Scotland are in sustained demand, particularly in Edinburgh where private clinic density is highest and patient volumes continue to grow.`,

    "Wales": `Wales has a smaller but growing private healthcare market, with the majority of activity based in Cardiff and Swansea. Independent practices across Wales have expanded as NHS waiting times have extended, creating consistent demand for qualified clinical staff. ${professionLabel} practitioners in Wales benefit from lower living costs than most English regions while accessing a patient base increasingly willing to pay for private healthcare services.`,

    "Northern Ireland": `Northern Ireland's private healthcare sector is centred on Belfast, where a number of private hospitals and independent clinic networks operate alongside the NHS. The region has seen increased private healthcare activity in recent years, with growing demand for specialist and aesthetic services. ${professionLabel} roles in Northern Ireland offer competitive salaries alongside a lower cost of living than mainland UK, making the region an increasingly attractive career destination.`,
  }

  return contexts[region] ?? `${professionLabel} roles in this region are advertised on The Practice Standard as practices across the UK seek qualified private healthcare professionals.`
}
